"use client";

import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useSession } from "next-auth/react";
import {
  Loader2,
  Download,
  Copy,
  Check,
  Lock,
  ArrowRight,
  ArrowLeft,
} from "lucide-react";

interface ToolField {
  key: string;
  label: string;
  placeholder?: string;
  type?: "text" | "textarea" | "select";
  options?: string[];
  required?: boolean;
  hint?: string;
}

interface DocumentToolProps {
  slug: string;
  documentType: string;
  title: string;
  description: string;
  fields: ToolField[];
  faqJson?: Array<{ q: string; a: string }>;
  seoDescription: string;
}

export function DocumentToolUI({
  slug,
  documentType,
  title,
  fields,
  seoDescription,
}: DocumentToolProps) {
  const { data: session } = useSession();
  const router = useRouter();

  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [content, setContent] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);
  const [step, setStep] = useState<"form" | "result">("form");
  const [upgradeRequired, setUpgradeRequired] = useState(false);

  function setField(key: string, value: string) {
    setAnswers((prev) => ({ ...prev, [key]: value }));
  }

  async function handleGenerate(e: React.FormEvent) {
    e.preventDefault();
    setError("");
    setUpgradeRequired(false);

    // Require login to generate
    if (!session?.user) {
      router.push(`/signup?redirect=/tools/${slug}`);
      return;
    }

    setLoading(true);
    try {
      const res = await fetch("/api/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ documentType, answers }),
      });

      const data = await res.json();

      if (!res.ok) {
        if (data.upgradeRequired) {
          setUpgradeRequired(true);
          setError(data.error);
        } else {
          setError(data.error ?? "Generation failed. Please try again.");
        }
      } else {
        setContent(data.content);
        setStep("result");
      }
    } catch {
      setError("Network error. Please check your connection and try again.");
    } finally {
      setLoading(false);
    }
  }

  async function handleCopy() {
    await navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  async function handleDownload() {
    if (!session?.user) {
      router.push(`/signup?redirect=/tools/${slug}`);
      return;
    }

    const res = await fetch("/api/pdf", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ content, title }),
    });

    if (res.ok) {
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${slug}-docuseal.pdf`;
      a.click();
      URL.revokeObjectURL(url);
    }
  }

  if (step === "result") {
    return (
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <h2 className="font-semibold text-foreground">
            Your {title} is ready
          </h2>
          <div className="flex gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 text-sm border border-border rounded-lg px-3 py-2 hover:bg-muted transition-colors"
            >
              {copied ? (
                <Check className="w-4 h-4 text-green-500" />
              ) : (
                <Copy className="w-4 h-4" />
              )}
              {copied ? "Copied!" : "Copy"}
            </button>
            <button
              onClick={handleDownload}
              className="flex items-center gap-1.5 text-sm gradient-primary text-white rounded-lg px-3 py-2 hover:opacity-90 transition-opacity"
            >
              <Download className="w-4 h-4" />
              Download PDF
            </button>
          </div>
        </div>

        <div className="relative bg-muted/50 border border-border rounded-xl p-6 min-h-96 font-mono text-sm text-foreground leading-relaxed overflow-auto max-h-[60vh] whitespace-pre-wrap">
          {content}
          {/* Watermark for free plan */}
          <div className="absolute bottom-4 right-4 text-xs text-muted-foreground/40 select-none pointer-events-none">
            Generated by DocuSeal.ai
          </div>
        </div>

        <div className="flex items-center justify-between">
          <button
            onClick={() => setStep("form")}
            className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors"
          >
            <ArrowLeft className="w-4 h-4" /> Edit answers
          </button>
          <Link
            href="/dashboard"
            className="flex items-center gap-1.5 text-sm text-primary hover:underline"
          >
            View all documents <ArrowRight className="w-4 h-4" />
          </Link>
        </div>

        <div className="bg-primary/5 border border-primary/20 rounded-xl p-4 text-sm">
          <p className="text-foreground font-medium mb-1">
            ⚡ Want unlimited documents + clean PDFs?
          </p>
          <p className="text-muted-foreground mb-3">
            Upgrade to Starter for $19/mo and remove all limits.
          </p>
          <Link
            href="/signup?plan=starter"
            className="inline-flex items-center gap-1.5 text-sm gradient-primary text-white font-medium px-4 py-2 rounded-lg hover:opacity-90 transition-opacity"
          >
            Start Free Trial <ArrowRight className="w-3.5 h-3.5" />
          </Link>
        </div>
      </div>
    );
  }

  return (
    <form onSubmit={handleGenerate} className="space-y-5">
      {error && (
        <div className="bg-destructive/10 border border-destructive/20 text-destructive text-sm rounded-lg px-4 py-3">
          {error}
          {upgradeRequired && (
            <div className="mt-2">
              <Link
                href="/signup?plan=starter"
                className="inline-flex items-center gap-1 text-primary font-medium hover:underline"
              >
                <Lock className="w-3.5 h-3.5" /> Upgrade to continue
              </Link>
            </div>
          )}
        </div>
      )}

      {fields.map((field) => (
        <div key={field.key}>
          <label className="block text-sm font-medium text-foreground mb-1.5">
            {field.label}
            {field.required && <span className="text-destructive ml-1">*</span>}
          </label>
          {field.hint && (
            <p className="text-xs text-muted-foreground mb-1.5">{field.hint}</p>
          )}
          {field.type === "textarea" ? (
            <textarea
              required={field.required}
              value={answers[field.key] ?? ""}
              onChange={(e) => setField(field.key, e.target.value)}
              placeholder={field.placeholder}
              rows={3}
              className="w-full px-3.5 py-2.5 border border-input rounded-xl text-sm bg-background text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring resize-none"
            />
          ) : field.type === "select" && field.options ? (
            <select
              required={field.required}
              value={answers[field.key] ?? ""}
              onChange={(e) => setField(field.key, e.target.value)}
              className="w-full px-3.5 py-2.5 border border-input rounded-xl text-sm bg-background text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
            >
              <option value="">Select one…</option>
              {field.options.map((o) => (
                <option key={o} value={o}>
                  {o}
                </option>
              ))}
            </select>
          ) : (
            <input
              type="text"
              required={field.required}
              value={answers[field.key] ?? ""}
              onChange={(e) => setField(field.key, e.target.value)}
              placeholder={field.placeholder}
              className="w-full px-3.5 py-2.5 border border-input rounded-xl text-sm bg-background text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring"
            />
          )}
        </div>
      ))}

      <button
        type="submit"
        disabled={loading}
        className="w-full gradient-primary text-white font-semibold py-3.5 rounded-xl text-sm hover:opacity-90 transition-opacity disabled:opacity-50 flex items-center justify-center gap-2"
      >
        {loading ? (
          <>
            <Loader2 className="w-4 h-4 animate-spin" />
            Generating with AI…
          </>
        ) : (
          <>Generate {title} Free</>
        )}
      </button>

      <p className="text-xs text-muted-foreground text-center">
        {!session?.user && "Creating an account is free and takes 30 seconds. "}
        Not legal advice — for informational purposes only.
      </p>
    </form>
  );
}
