import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/auth";

export async function POST(req: NextRequest) {
  const { content, title } = await req.json();

  if (!content) {
    return NextResponse.json({ error: "No content provided" }, { status: 400 });
  }

  const session = await auth();
  const isWatermarked = !session?.user;

  // Build simple HTML document for PDF
  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: Georgia, serif; font-size: 12px; line-height: 1.7; color: #1a1a1a; max-width: 700px; margin: 40px auto; padding: 20px; }
  h1 { font-size: 20px; margin-bottom: 4px; }
  h2 { font-size: 14px; margin-top: 24px; margin-bottom: 6px; }
  p { margin: 0 0 10px; }
  .watermark { position: fixed; bottom: 20px; right: 20px; font-size: 10px; color: #ccc; font-family: sans-serif; }
  .header { border-bottom: 2px solid #7c3aed; padding-bottom: 12px; margin-bottom: 24px; }
  .meta { font-size: 11px; color: #666; margin-top: 4px; }
</style>
</head>
<body>
  <div class="header">
    <h1>${title ?? "Legal Document"}</h1>
    <div class="meta">Generated by DocuSeal.ai on ${new Date().toLocaleDateString("en-US", { dateStyle: "long" })}</div>
  </div>
  <div>${content.replace(/\n/g, "<br>").replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>").replace(/^# (.+)$/gm, "<h1>$1</h1>").replace(/^## (.+)$/gm, "<h2>$1</h2>").replace(/^### (.+)$/gm, "<h3>$1</h3>")}</div>
  ${isWatermarked ? '<div class="watermark">Generated with DocuSeal.ai — docuseal.ai</div>' : ""}
  <div style="margin-top:40px;padding-top:16px;border-top:1px solid #eee;font-size:10px;color:#999;font-family:sans-serif;">
    This document was generated by DocuSeal AI and is provided for informational purposes only. It does not constitute legal advice. Consult a licensed attorney for legal matters.
  </div>
</body>
</html>`;

  // Return HTML with proper headers — browser can print-to-PDF
  // For production, use puppeteer/playwright on a server
  return new NextResponse(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Disposition": `attachment; filename="${(title ?? "document").toLowerCase().replace(/\s+/g, "-")}.html"`,
    },
  });
}
